// images
export const GET_IMAGES = 'GET_IMAGES';
export const RESET_IMAGE_STORE = 'RESET_IMAGE_STORE';
export const INCREMENT_IMAGE_PAGE = 'INCREMENT_IMAGE_PAGE';
export const IS_LOADING = 'IS_LOADING';

// favorites
export const MAKE_FAVORITE = 'MAKE_FAVORITE';
export const GET_FAVORITE = 'GET_FAVORITE';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const RESET_FAVORITES = 'RESET_FAVORITES';